production:
  host: us-cdbr-east-05.cleardb.net
  port: 3306
  username: baa6fe19cd211b
  password: c2e1c2f0
  dbname: heroku_00e2bbcdfaea45e

development:
  host: localhost
  port: 3306
  username: root
  password:
  dbname: happy_reminder

