development:
  facebook:
    app_id: "238056306352235"
    app_secret: "9653876819c5f43806a45328598da361"
    callback: "http://happy-remind.local:8888/facebook/callback"

production:
  facebook:
    app_id: "417061785062564"
    app_secret: "797d3b9407100cb55a3b66d85b395eb1"
    callback: "http://happy-reminder.herokuapp.com/facebook/callback"